# AWS コスト詳細レポート設定ファイル

# AWS リージョン設定
regions:
  # 対象リージョン（カンマ区切り、または'all'）
  include: "all"
  # 除外リージョン（カンマ区切り）
  exclude: ""

# コスト分析設定
cost_analysis:
  # リソースのタグ情報を収集する
  collect_tags: true
  # タグ情報収集時の同時実行数
  tag_collection_threads: 10

# 出力設定
output:
  # デフォルト出力形式（console, csv, html）
  default_format: "console"
  # レポートのタイトル
  title: "AWS コスト詳細レポート"
  # HTMLレポートのスタイル設定
  html_style:
    # 背景色
    background_color: "#ffffff"
    # テーブルヘッダーの背景色
    header_color: "#f2f2f2"
    # テーブル罫線の色
    border_color: "#dddddd"
