version: '3'

tasks:
  setup:
    desc: セットアップ - 仮想環境と依存パッケージのインストール
    cmds:
      - rm -rf .venv || true
      - python -m venv .venv
      - bash -c '. .venv/bin/activate && pip install -r requirements.txt'
    silent: false

  run:
    desc: AWSリソース棚卸しツールを実行
    cmds:
      - bash -c '. .venv/bin/activate && python src/main.py {{.CLI_ARGS}}'
    silent: false

  run:csv:
    desc: CSV形式のみでリソース棚卸しを実行
    cmds:
      - task: run
        vars:
          CLI_ARGS: --format csv
    silent: false

  run:json:
    desc: JSON形式のみでリソース棚卸しを実行
    cmds:
      - task: run
        vars:
          CLI_ARGS: --format json
    silent: false

  run:both:
    desc: CSV+JSON形式で棚卸しを実行（デフォルト）
    cmds:
      - task: run
        vars:
          CLI_ARGS: --format both
    silent: false

  run:region:
    desc: 特定のリージョンで棚卸しを実行
    cmds:
      - task: run -- --region {{.REGION}}

  run:profile:
    desc: 特定のAWSプロファイルで棚卸しを実行
    cmds:
      - task: run
        vars:
          CLI_ARGS: --profile {{.PROFILE}}
    silent: false

  update-deps:
    desc: 依存パッケージを更新
    cmds:
      - bash -c '. .venv/bin/activate && pip install -U -r requirements.txt'
    silent: false

  clean:
    desc: 生成されたレポートファイルをクリーン
    cmds:
      - rm -rf output/*
    silent: false

  test:
    desc: テストを実行
    cmds:
      - bash -c '. .venv/bin/activate && pytest'
    silent: false

  lint:
    desc: コードリンティングを実行
    cmds:
      - bash -c '. .venv/bin/activate && flake8 src/'
    silent: false

  format:
    desc: コードフォーマッティングを実行
    cmds:
      - bash -c '. .venv/bin/activate && autoflake --remove-all-unused-imports --recursive --in-place src/ && isort src/ && black src/'
    silent: false

  isort:
    desc: インポート文の整理を実行
    cmds:
      - bash -c '. .venv/bin/activate && isort src/'
    silent: false

  autoflake:
    desc: 未使用のインポートを削除
    cmds:
      - bash -c '. .venv/bin/activate && autoflake --remove-all-unused-imports --recursive --in-place src/'
    silent: false

  install-dev:
    desc: 開発用依存パッケージをインストール
    cmds:
      - bash -c '. .venv/bin/activate && pip install -r requirements-dev.txt'
    silent: false

  examples:
    desc: 使用例を表示
    cmds:
      - echo "# AWS リソース棚卸しツール使用例"
      - echo "task run               # デフォルト設定で実行"
      - echo "task run:csv           # CSV形式のみで出力"
      - echo "task run:json          # JSON形式のみで出力"
      - echo "task run:region REGION=ap-northeast-1   # 東京リージョンで実行"
      - echo "task run:profile PROFILE=production     # 本番環境プロファイルで実行"
      - echo "task run -- --profile production --region ap-northeast-1   # カスタムパラメータ指定"
    silent: false

  list-services:
    desc: 対応しているサービス一覧を表示
    cmds:
      - echo "# AWS リソース棚卸しツール - 対応サービス一覧"
      - echo "- Amazon EC2（インスタンス、ボリューム、セキュリティグループ、ロードバランサーなど）"
      - echo "- Amazon S3（バケット）"
      - echo "- Amazon RDS（DBインスタンス、DBクラスター、スナップショットなど）"
      - echo "- AWS Lambda（関数、レイヤー、イベントソースマッピング）"
      - echo "- Amazon DynamoDB（テーブル、グローバルテーブル、バックアップ）"
      - echo "- Amazon CloudFront（ディストリビューション、キャッシュポリシーなど）"
      - echo "- Amazon Route 53（ホストゾーン、ヘルスチェック、ドメインなど）"
      - echo "- AWS IAM（ユーザー、グループ、ロール、ポリシーなど）"
      - echo "- Amazon CloudWatch（アラーム、ダッシュボード、ロググループ、イベントルール）"
      - echo "- Amazon ElastiCache（クラスター、レプリケーショングループなど）"
      - echo "- Amazon SNS（トピック、サブスクリプション）"
      - echo "- Amazon SQS（キュー）"
    silent: false
